### ISSUE TITLE
Problem when tracing back orginal genomes

### ISSUE THREAD

**Issue by fjell-dev** [shenwei356/LexicMap#11]
Hi, maybe I missed something but I followed the guide for indexing GTDB and searched the index against my genes of interest. However, when I tried to find the taxnonomy information of the hit genomes, apparently I could not find them through grepping the assembly_summary.text. For example, in the output I got there are some ID such as CAKQHN010000007.1 and CASJNN010000412.1 which were not found in the file, or even when I searched on the GTDB website.
Could you be able to help me with the issue?
Thanks a lot.

**Comment by shenwei356** [comment]
CAKQHN010000007.1 should be the sequence ID, you need to use the column (genome ID) before it to search :)

**Comment by shenwei356** [comment]
https://bioinf.shenwei.me/LexicMap/tutorials/search/#output-format

```
1.  query,    Query sequence ID.
2.  qlen,     Query sequence length.
3.  hits,     Number of subject genomes.
4.  sgenome,  Subject genome ID.
5.  sseqid,   Subject sequence ID.
```
