### ISSUE TITLE
Does LexicMap gives result with paried end fastq data and abundance score ?

### ISSUE THREAD

**Issue by arpit20328** [shenwei356/LexicMap#6]
I have paired end data out of illumina in fastq format 

like file_R1.fastq and file_R2.fastq 

Does LexicMap gives result with paried end fastq data and abundance score ? 

I have indexed my reference database as per lexicMap protocol

**Comment by shenwei356** [comment]
> [Does LexicMap support short reads?](https://bioinf.shenwei.me/LexicMap/faqs/#does-lexicmap-support-short-reads)
> 
> LexicMap is mainly designed for sequence alignment with a small number of queries (gene/plasmid/virus/phage sequences) longer than 200 bp by default.

Dear @arpit20328, LexicMap is not designed for paired-end short reads.  And no abundance information is outputted. 

If you're looking for metagenomic profiling tools, have a look at my [KMCP](https://github.com/shenwei356/kmcp)
