### ISSUE TITLE
Can Lexicmap Be Used With A Single File Containing Merged Genomes

### ISSUE THREAD

**Issue by Dx-wmc** [shenwei356/LexicMap#8]
Hi, I am currently downloading the NCBI nt database and planning to use lexicmap for its construction. However, according to the help documentation, lexicmap appears to be suitable for cases where multiple genomes are stored in separate files within a folder. Does this imply that lexicmap cannot be used if all genomes are merged into a single file?

**Comment by shenwei356** [comment]
You're right.

And please note that: nt database has genomes from microbes, plants and humans, while **LexicMap is mainly for microbial genomes**.

One more thing: nt database only has a very small part of available bacteria genomes. See Figure 1a here https://www.biorxiv.org/content/10.1101/2023.04.15.536996v3.full 

![image](https://github.com/user-attachments/assets/ee218ac3-c018-4ae6-95b8-aa5d4b79c9d7)

**Comment by shenwei356** [comment]
Besides, LexicMap outputs [a metric](https://bioinf.shenwei.me/LexicMap/tutorials/search/#output-format) related to the whole genome. It is important for searching queries like plasmids against fragmented assemblies, which are very common and hard to be properly organised in a huge file like nt.fasta. Therefore, LexicMap (and KMCP) requires input genomes saved in separate files.

```
6.  qcovGnm,  Query coverage (percentage) per genome: $(aligned bases in the genome)/$qlen.
```

**Comment by shenwei356** [comment]
Technically, LexicMap indexes each genome as a whole instead of indexing individual sequences. This makes LexicMap more scalable than tools like Blastn, by reducing the scale of targets to be indexed.

**Comment by shenwei356** [comment]
https://github.com/pirovc/genome_updater is recommended to download assemblies from Refseq/Genbank/GTDB.

**Comment by Dx-wmc** [comment]
Thank you for your detailed response to this issue. I also work in the field of microbiology, but I find it easier to construct the nt database because there is only one dataset. Your advice has been very helpful to me, and I am ready to try downloading genomes that are only related to microbiology for further experimentation.

**Comment by Dx-wmc** [comment]
Hi, I noticed that lexicmap seems to have requirements for the names of genomes from genbank, but I tried running it without modifying the names (for example: GCF_000003135.1_ASM313v1_genomic.fna.gz) and it worked fine. Is this really feasible?

**Comment by shenwei356** [comment]
It's OK.  The only "side effect" would be that the `sgenome` column would be too wide in `lexicmap search` results.


<hr>

You might have read the following guidance on the filename and genome IDs. https://bioinf.shenwei.me/LexicMap/tutorials/index/#input

- **File name**: "Genome ID" + "File extention". E.g., `GCF_000006945.2.fna.gz`.
    - **Genome ID**: **they must not contain tab ("\t") symbols, and should be distinct for accurate result interpretation**, which will be shown in the search result.
        - A regular expression is also available to extract reference id from the file name.
          E.g., `--ref-name-regexp '^(\w{3}_\d{9}\.\d+)'` extracts `GCF_000006945.2` from GenBank assembly file `GCF_000006945.2_ASM694v2_genomic.fna.gz`

**Comment by Dx-wmc** [comment]
Thanks for the clarification. I also encountered an error when building the GenBank database, what does this mean: `[ERRO] read seq 106 in 2024-10-27_19-37-42/files/GCF_018999785.1_ASM1899978v1_genomic.fna.gz: unexpected EOF`. The command I used to index is: `lexicmap index -I 2024-10-27_19-37-42/files/ --ref-name-regexp '^(\w{3}_\d{9}\.\d+)' -O lexicmap/refseq.241027.lmi -j 50 -b 25000`

**Comment by shenwei356** [comment]
Some files could corrupt during downloading, we recommend checking sequence file integrity using seqkit

Follow this: https://bioinf.shenwei.me/kmcp/faq/#unexpected-eof-error

1. Find corrupted files.
2. Delete them.
3. Add `-` for https://github.com/pirovc/genome_updater, to re-download them.

**Comment by Dx-wmc** [comment]
You are right, I checked the size of the problematic sequence and found that it is much smaller than normal.

**Comment by Dx-wmc** [comment]
Hi, I have successfully installed and configured the database, and I have used the gene search, which works well. However, it seems that lexicmap cannot perform searches at the level of the entire genome size (e.g. a chromosome of 4M). So what's the maximum segment size that lexicmap can compare?

**Comment by shenwei356** [comment]
LexicMaps finds all local alignments between a query and target genomes.  There is no such maximum segment size; the length of alignments depends on the query's sequence complexity and the similarity between the query and target genomes.

With longer queries, such as a chromosome longer than 1Mb, there are bigger differences between a query and targets. It's hard to return an ultra-long alignment of 1Mb.

**Comment by Dx-wmc** [comment]
Thanks for the clarification, looking forward to lexicmaps developing better, after all it's really super fast!

**Comment by shenwei356** [comment]
If you have any questions, please do not hesitate to contact me via GitHub, email, or WeChat (shenwei356).
