### ISSUE TITLE
Runtime error index out of range for Lexicmap search

### ISSUE THREAD

**Issue by andhamel** [shenwei356/LexicMap#9]
Hi all,

I was running `lexicmap search` with the parameters recommended in the tutorial, and for one fasta I received this error message

```
Panic: runtime error index of out range [X] with length X
```

where X is the length of my aligned length with my query. I think this is due to the gap size as when I lowered `- -align-min-gap` the software ran successfully. Has this been encountered before? Also, this error only happens when I have the `-a` option, which leads me to think it has to do with writing the output potentially for the cigar string.

**Comment by shenwei356** [comment]
Hi, thanks for reporting this. Please paste the whole error information, which show the line number of the code which panic. Or please provide the query sequence and index information.

**Comment by andhamel** [comment]
Here is the full error message:

```
panic: runtime error: index out of range [237] with length 237

goroutine 10872 [running]:
github.com/shenwei356/wfa.(*AlignmentResult).AlignmentText(0xc0439c9e00, 0xc03399ee00, 0xc03399ede8)
	/home/shenwei/go/pkg/mod/github.com/shenwei356/wfa@v0.3.0/wfa_cigar.go:240 +0x3ff
github.com/shenwei356/LexicMap/lexicmap/cmd.(*Index).Search.func7(0xc00e2c1c20)
	/home/shenwei/go/src/github.com/shenwei356/LexicMap/lexicmap/cmd/lib-index-search.go:1731 +0x28dd
created by github.com/shenwei356/LexicMap/lexicmap/cmd.(*Index).Search in goroutine 9602
	/home/shenwei/go/src/github.com/shenwei356/LexicMap/lexicmap/cmd/lib-index-search.go:1182 +0xdec
```

I hope this helps! Thank you for the response.

**Comment by shenwei356** [comment]
Emm, it's not sufficient for debug. It would help if you provide the query seq and a few target seqs/genomes (you said it works without -a). You can   send them via email ( shenwei356@gmail.com ) if you want to keep them private. I'll try to fix them tomorrow.

**Comment by shenwei356** [comment]
According to the sequences provided by @andhamel , I confirm it's a bug in the alignment output steps, which happens for queries with highly repetitive sequences in flanking regions.

It's fixed now, please test it.

- [lexicmap_darwin_amd64.tar.gz](https://github.com/user-attachments/files/17584580/lexicmap_darwin_amd64.tar.gz)
- [lexicmap_darwin_arm64.tar.gz](https://github.com/user-attachments/files/17584585/lexicmap_darwin_arm64.tar.gz)
- [lexicmap_linux_amd64.tar.gz](https://github.com/user-attachments/files/17584587/lexicmap_linux_amd64.tar.gz)
- [lexicmap_windows_amd64.exe.tar.gz](https://github.com/user-attachments/files/17584588/lexicmap_windows_amd64.exe.tar.gz)

**Comment by shenwei356** [comment]
Please use v0.5.0: https://github.com/shenwei356/LexicMap/releases/tag/v0.5.0
